name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps: 
      - name: Image Scanning vulnerable
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
        run: 
          C:\TMAS\tmas.exe aiscan llm -c Scanner.yaml

      - name: Image Scanning protegido
        run:
          C:\tmas\tmas.exe aiscan llm -c config-protected.yaml `
      
      - name: Reporte
        run:
          Invoke-Item report-vuln.md
          Invoke-Item report-prot.md
